version: "3.8"

services:

  postgres-rinha:
    image: postgres:16-alpine
    container_name: postgres-rinha
    environment:
      - POSTGRES_DB=rinha-backend
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - "5434:5432"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '220MB'
    volumes:
      - ./docker-entrypoint-initdb.d/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - spring

  api1: &api
    container_name: api1
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - postgres-rinha
    environment:
      - SERVER_PORT=8080
      - POSTGRES_HOST=postgres-rinha
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '150MB'
    networks:
      - spring

  api2:
    <<: *api
    container_name: api2

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '30MB'
    networks:
      - spring

networks:
  spring:
    driver: bridge