version: "3.8"

services:

  postgres-rinha:
    image: postgres
    container_name: postgres-rinha
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - "5434:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d postgres-rinha" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - spring

  api1: &api
    container_name: api1
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - postgres-rinha
    environment:
      - POSTGRES_HOST=postgres-rinha
    networks:
      - spring

  api2:
    <<: *api
    container_name: api2

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - spring

networks:
  spring:
    driver: bridge