logging:
  level:
    root: WARN

spring:
  application:
    name: rinha-de-backend-java
  banner:
    location: rinha-java.txt
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${DB_PORT:5432}/rinha-backend
    username: ${POSTGRES_USER:root}
    password: ${POSTGRES_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  mvc:
    async:
      request-timeout: 600000